### ISSUE TITLE
It

### ISSUE THREAD

**Issue by Princy2004** [kcubeterm/blackeye#2]

**Comment by kcubeterm** [comment]
Look like you are learning github stuff, cool 

Keep it up

**Comment by Princy2004** [comment]
Yeah. It is really difficult

**Comment by kcubeterm** [comment]
Nope, it's not difficult,

**Comment by Princy2004** [comment]
I tried to choose an option but I didn't get the link

**Comment by kcubeterm** [comment]
For link, forward your 8080 port.
For example with ngrok.
```ngrok http 8080```

**Comment by Princy2004** [comment]
Oh ok... I have to restart the whole process again because I closed the
session
